language: php

php:
  - 5.5
  - 5.6

services:
  - mongodb

before_script:
  - echo 'extension = mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer install

script:
    - vendor/bin/phpunit 
